# Generated by Django 5.0.14 on 2026-07-23 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_part_sku_alter_part_unit_alter_part_unit_price_and_more'),
        ('organizations', '0002_organization_invoice_code'),
        ('service', '0004_move_inventory_models_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=50, verbose_name='Nomor Invoice')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('year', models.PositiveIntegerField(editable=False, verbose_name='Tahun')),
                ('customer_name_snapshot', models.CharField(max_length=200, verbose_name='Nama Pelanggan')),
                ('license_plate_snapshot', models.CharField(max_length=20, verbose_name='Nomor Plat')),
                ('status', models.CharField(choices=[('DRAFT', 'Draf'), ('ISSUED', 'Diterbitkan'), ('PAID', 'Lunas'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deposit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('service_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='service.servicerecord', verbose_name='Catatan Servis')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('part', 'Part'), ('labor', 'Jasa')], max_length=10, verbose_name='Jenis')),
                ('description', models.CharField(max_length=255, verbose_name='Deskripsi')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Jumlah')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoicing.invoice', verbose_name='Invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_items', to='inventory.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='Tahun')),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Invoice Sequence',
                'verbose_name_plural': 'Invoice Sequences',
                'unique_together': {('organization', 'year')},
            },
        ),
    ]
