# Generated by Django 5.0.14 on 2026-07-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mechanic_name_snapshot',
            field=models.CharField(default='(Invoice lama, mekanik tidak tercatat)', max_length=200, verbose_name='Nama Mekanik'),
            preserve_default=False,
        ),
    ]
