# Generated by Django 5.0.14 on 2026-08-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoice_mechanic_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issued_event_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='ID Event Penerbitan'),
        ),
    ]
