# Generated by Django 5.0.14 on 2026-09-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_issued_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draf'), ('ISSUED', 'Diterbitkan'), ('PARTIALLY_PAID', 'Dibayar Sebagian'), ('PAID', 'Lunas'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
