# =============================================================================
# === backend/apps/inventory/migrations/0002_alter_part_sku_alter_part_unit_alter_part_unit_price_and_more.py ===
# Closes the drift between the hand-written 0001_initial (which
# recreated Part/PartUsage/StockAdjustment's migration STATE during
# the apps.service -> apps.inventory move) and the actual models.py.
# Two harmless, zero-schema-impact changes:
#   1. help_text was omitted from sku/unit/unit_price in 0001's
#      hand-written CreateModel — help_text is form/admin display
#      metadata only, never stored in the database, so these
#      AlterField ops generate no real SQL.
#   2. 0001 explicitly pinned db_table to "inventory_part" etc.
#      Django's autodetector treats "explicitly set to X" and "not
#      set, defaults to X" as different states even when X is
#      identical — inventory_part IS Django's own default table name
#      for a Part model in the inventory app. Removing the explicit
#      pin changes nothing physically.
# Generated by `python manage.py makemigrations inventory` — content
# below is Django's own real output, not hand-written.
# =============================================================================
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.CharField(blank=True, help_text='Opsional — kode internal bengkel untuk part ini, jika ada.', max_length=50, verbose_name='Kode/SKU'),
        ),
        migrations.AlterField(
            model_name='part',
            name='unit',
            field=models.CharField(default='pcs', help_text='pcs, liter, set, botol, dll.', max_length=20, verbose_name='Satuan'),
        ),
        migrations.AlterField(
            model_name='part',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Harga jual per satuan saat ini — perubahan di sini tidak mengubah riwayat pemakaian yang sudah tercatat.', max_digits=12, verbose_name='Harga Satuan'),
        ),
        migrations.AlterModelTable(
            name='part',
            table=None,
        ),
        migrations.AlterModelTable(
            name='partusage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stockadjustment',
            table=None,
        ),
    ]
