# Generated by Django 5.0.14 on 2026-07-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_part_sku_alter_part_unit_alter_part_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('restock', 'Restock / Pembelian'), ('correction', 'Koreksi Stok'), ('damage', 'Rusak / Hilang'), ('work_order_cancelled', 'Pembatalan Work Order')], default='restock', max_length=20, verbose_name='Alasan'),
        ),
    ]
