# Generated by Django 5.0.14 on 2026-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockadjustment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('restock', 'Restock / Pembelian'), ('correction', 'Koreksi Stok'), ('damage', 'Rusak / Hilang'), ('work_order_cancelled', 'Pembatalan Work Order'), ('customer_cancelled_part', 'Part Dibatalkan Pelanggan')], default='restock', max_length=30, verbose_name='Alasan'),
        ),
    ]
