# Generated by Django 5.0.14 on 2026-08-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_minimum_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('restock', 'Restock / Pembelian'), ('correction', 'Koreksi Stok'), ('damage', 'Rusak / Hilang'), ('work_order_cancelled', 'Pembatalan Work Order'), ('customer_cancelled_part', 'Part Dibatalkan Pelanggan'), ('purchase_return', 'Retur Pembelian')], default='restock', max_length=30, verbose_name='Alasan'),
        ),
    ]
