# Generated by Django 5.0.14 on 2026-08-22 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_part_taxonomy_reorder_cadence'),
        ('organizations', '0004_organization_daily_appointment_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOpnameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor Opname')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Selesai')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Stock Opname Session',
                'verbose_name_plural': 'Stock Opname Sessions',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='StockOpnameSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Stock Opname Sequence',
                'verbose_name_plural': 'Stock Opname Sequences',
                'unique_together': {('organization',)},
            },
        ),
        migrations.CreateModel(
            name='StockOpnameLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_stock_at_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stok Sistem Saat Mulai')),
                ('physical_count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hasil Hitung Fisik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_opname_lines', to='inventory.part', verbose_name='Part')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='inventory.stockopnamesession', verbose_name='Sesi Stock Opname')),
            ],
            options={
                'verbose_name': 'Stock Opname Line Item',
                'verbose_name_plural': 'Stock Opname Line Items',
                'ordering': ['created_at'],
                'unique_together': {('session', 'part')},
            },
        ),
    ]
