# Generated by Django 5.0.14 on 2026-08-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockopnamesession_stockopnamesequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Harga pokok (cost) terakhir dari GRN — diperbarui otomatis, tidak bisa diisi manual. 0 berarti part ini belum pernah menerima GRN.', max_digits=12, verbose_name='Harga Beli (HPP)'),
        ),
    ]
