# Generated by Django 5.0.14 on 2026-09-14 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stockadjustment_reason'),
        ('organizations', '0006_organization_requires_sequential_period_closing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartFieldChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50, verbose_name='Nama Field')),
                ('field_label', models.CharField(max_length=100, verbose_name='Label Field')),
                ('old_value', models.TextField(blank=True, verbose_name='Nilai Lama')),
                ('new_value', models.TextField(blank=True, verbose_name='Nilai Baru')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='inventory.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Part Field Change',
                'verbose_name_plural': 'Part Field Changes',
                'ordering': ['-changed_at'],
            },
        ),
    ]
