# Generated by Django 5.0.14 on 2026-07-25 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_stockadjustment_reason'),
        ('organizations', '0002_organization_invoice_code'),
        ('service', '0004_move_inventory_models_out'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=20, verbose_name='Nomor Estimasi')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20, verbose_name='Status')),
                ('diagnosis_notes', models.TextField(blank=True, verbose_name='Catatan Diagnosa')),
                ('rejection_reason', models.CharField(blank=True, choices=[('TOO_EXPENSIVE', 'Harga Terlalu Mahal'), ('WENT_ELSEWHERE', 'Pilih Bengkel Lain'), ('POSTPONED', 'Ditunda Dulu'), ('NOT_NEEDED', 'Diputuskan Tidak Perlu'), ('OTHER', 'Lainnya')], max_length=20, verbose_name='Alasan Penolakan')),
                ('rejection_notes', models.TextField(blank=True, verbose_name='Catatan Penolakan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='service.vehicle', verbose_name='Kendaraan')),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate', to='workorders.workorder', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'Estimate',
                'verbose_name_plural': 'Estimates',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('part', 'Part'), ('labor', 'Jasa')], max_length=10, verbose_name='Jenis')),
                ('description', models.CharField(max_length=255, verbose_name='Deskripsi')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Jumlah')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='estimates.estimate', verbose_name='Estimasi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_line_items', to='inventory.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Estimate Line Item',
                'verbose_name_plural': 'Estimate Line Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Estimate Sequence',
                'verbose_name_plural': 'Estimate Sequences',
                'unique_together': {('organization',)},
            },
        ),
    ]
