# Generated by Django 5.0.14 on 2026-07-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='odometer_km_intake',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Saat Masuk'),
        ),
    ]
