# Generated by Django 5.0.14 on 2026-08-07 02:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_invoice_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='Kode Akun')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Akun')),
                ('account_type', models.CharField(choices=[('ASSET', 'Aset'), ('LIABILITY', 'Kewajiban'), ('EQUITY', 'Ekuitas'), ('REVENUE', 'Pendapatan'), ('COGS', 'Harga Pokok Penjualan'), ('EXPENSE', 'Beban')], max_length=20, verbose_name='Tipe Akun')),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Kredit')], max_length=10, verbose_name='Saldo Normal')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Ditutup')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Terkunci')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Accounting Period',
                'verbose_name_plural': 'Accounting Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(editable=False, max_length=30, verbose_name='Nomor Jurnal')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('posting_date', models.DateField(verbose_name='Tanggal Posting')),
                ('source', models.CharField(choices=[('DOMAIN_EVENT', 'Event Domain'), ('MANUAL', 'Jurnal Manual')], max_length=20, verbose_name='Sumber')),
                ('event_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipe Event')),
                ('reference_event_id', models.UUIDField(blank=True, null=True, verbose_name='ID Event Rujukan')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu'), ('VALIDATED', 'Tervalidasi'), ('POSTED', 'Terposting')], default='POSTED', max_length=20, verbose_name='Status')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingperiod', verbose_name='Periode Akuntansi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-posting_date', '-sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntrySequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Journal Entry Sequence',
                'verbose_name_plural': 'Journal Entry Sequences',
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Debit')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Kredit')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='Akun')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='Entri Jurnal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Journal Line',
                'verbose_name_plural': 'Journal Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='accountingperiod_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('organization', 'entry_number')},
        ),
        migrations.AlterUniqueTogether(
            name='journalentrysequence',
            unique_together={('organization',)},
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit_amount', 0), ('debit_amount__gt', 0)), models.Q(('credit_amount__gt', 0), ('debit_amount', 0)), _connector='OR'), name='journalline_exactly_one_side'),
        ),
    ]
