# Generated by Django 5.0.14 on 2026-08-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('organizations', '0004_organization_daily_appointment_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Accounting Period', 'verbose_name_plural': 'Accounting Periods'},
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='month',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Bulan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='year',
            field=models.PositiveIntegerField(default=1, verbose_name='Tahun'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('organization', 'year', 'month')},
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1), ('month__lte', 12)), name='accountingperiod_month_valid_range'),
        ),
    ]
