# Generated by Django 5.0.14 on 2026-08-28 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_migrate_to_monthly_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Ditutup'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ditutup Oleh'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dibuka Kembali'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dibuka Kembali Oleh'),
        ),
    ]
