# Generated by Django 5.0.14 on 2026-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingperiod_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('DOMAIN_EVENT', 'Event Domain'), ('MANUAL', 'Jurnal Manual'), ('PERIOD_CLOSING', 'Penutupan Periode')], max_length=20, verbose_name='Sumber'),
        ),
    ]
