# Generated by Django 5.0.14 on 2026-08-29 12:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalentry_source'),
        ('organizations', '0004_organization_daily_appointment_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('DOMAIN_EVENT', 'Event Domain'), ('MANUAL', 'Jurnal Manual'), ('PERIOD_CLOSING', 'Penutupan Periode'), ('ASSET_ACQUISITION', 'Perolehan Aset'), ('DEPRECIATION', 'Penyusutan Aset')], max_length=20, verbose_name='Sumber'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor Aset')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Aset')),
                ('acquisition_date', models.DateField(verbose_name='Tanggal Perolehan')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Perolehan')),
                ('useful_life_months', models.PositiveIntegerField(verbose_name='Umur Manfaat (Bulan)')),
                ('method', models.CharField(choices=[('straight_line', 'Garis Lurus')], default='straight_line', max_length=20, verbose_name='Metode Penyusutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-acquisition_date'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DepreciationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total Penyusutan')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_runs', to='accounting.accountingperiod', verbose_name='Periode Akuntansi')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_run', to='accounting.journalentry', verbose_name='Jurnal Penyusutan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Depreciation Run',
                'verbose_name_plural': 'Depreciation Runs',
                'unique_together': {('organization', 'accounting_period')},
            },
        ),
        migrations.CreateModel(
            name='AssetSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Asset Sequence',
                'verbose_name_plural': 'Asset Sequences',
                'unique_together': {('organization',)},
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah Penyusutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='accounting.asset', verbose_name='Aset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('depreciation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.depreciationrun', verbose_name='Penyusutan Bulan Ini')),
            ],
            options={
                'verbose_name': 'Asset Depreciation Entry',
                'verbose_name_plural': 'Asset Depreciation Entries',
                'ordering': ['created_at'],
                'unique_together': {('asset', 'depreciation_run')},
            },
        ),
    ]
