# Generated by Django 5.0.14 on 2026-09-03 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_journalentry_source_asset_depreciationrun_and_more'),
        ('inventory', '0011_alter_stockadjustment_reason'),
        ('organizations', '0005_organization_address_and_more'),
        ('purchasing', '0007_supplierinvoice_attachment_quickpurchase_and_more'),
        ('service', '0007_servicereminderlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('DOMAIN_EVENT', 'Event Domain'), ('MANUAL', 'Jurnal Manual'), ('PERIOD_CLOSING', 'Penutupan Periode'), ('ASSET_ACQUISITION', 'Perolehan Aset'), ('DEPRECIATION', 'Penyusutan Aset'), ('OPENING_BALANCE', 'Saldo Awal')], max_length=20, verbose_name='Sumber'),
        ),
        migrations.CreateModel(
            name='OpeningBalanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai Akuntansi')),
                ('status', models.CharField(choices=[('DRAFT', 'Draf'), ('POSTED', 'Terposting')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Diposting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_session', to='accounting.journalentry', verbose_name='Jurnal Saldo Awal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Diposting Oleh')),
            ],
            options={
                'verbose_name': 'Opening Balance Session',
                'verbose_name_plural': 'Opening Balance Sessions',
                'unique_together': {('organization',)},
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Piutang')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referensi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_receivables', to='service.customer', verbose_name='Pelanggan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_lines', to='accounting.openingbalancesession', verbose_name='Sesi Saldo Awal')),
            ],
            options={
                'verbose_name': 'Opening Balance Receivable',
                'verbose_name_plural': 'Opening Balance Receivables',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalancePayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Utang')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referensi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_payables', to='purchasing.supplier', verbose_name='Supplier')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable_lines', to='accounting.openingbalancesession', verbose_name='Sesi Saldo Awal')),
            ],
            options={
                'verbose_name': 'Opening Balance Payable',
                'verbose_name_plural': 'Opening Balance Payables',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalancePartLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=200, verbose_name='Nama Part')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='Kode/SKU')),
                ('unit', models.CharField(default='pcs', max_length=20, verbose_name='Satuan')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Pokok Awal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_line', to='inventory.part', verbose_name='Part (setelah diposting)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_lines', to='accounting.openingbalancesession', verbose_name='Sesi Saldo Awal')),
            ],
            options={
                'verbose_name': 'Opening Balance Part Line',
                'verbose_name_plural': 'Opening Balance Part Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceOtherLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=10, verbose_name='Kode Akun')),
                ('side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Kredit')], max_length=10, verbose_name='Sisi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jumlah')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lines', to='accounting.openingbalancesession', verbose_name='Sesi Saldo Awal')),
            ],
            options={
                'verbose_name': 'Opening Balance Other Line',
                'verbose_name_plural': 'Opening Balance Other Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceAssetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Aset')),
                ('current_book_value', models.DecimalField(decimal_places=2, help_text='Nilai aset SAAT INI, bukan harga beli aslinya — berapa nilai aset ini hari ini.', max_digits=12, verbose_name='Nilai Buku Saat Ini')),
                ('remaining_useful_life_months', models.PositiveIntegerField(help_text='Berapa bulan lagi aset ini diperkirakan masih bisa dipakai, mulai dari sekarang.', verbose_name='Sisa Umur Manfaat (Bulan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_line', to='accounting.asset', verbose_name='Aset (setelah diposting)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_lines', to='accounting.openingbalancesession', verbose_name='Sesi Saldo Awal')),
            ],
            options={
                'verbose_name': 'Opening Balance Asset Line',
                'verbose_name_plural': 'Opening Balance Asset Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceCashLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(choices=[('1001', 'Kas'), ('1101', 'Bank')], max_length=10, verbose_name='Akun')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jumlah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_lines', to='accounting.openingbalancesession', verbose_name='Sesi Saldo Awal')),
            ],
            options={
                'verbose_name': 'Opening Balance Cash Line',
                'verbose_name_plural': 'Opening Balance Cash Lines',
                'unique_together': {('session', 'account_code')},
            },
        ),
    ]
