# Generated by Django 5.0.14 on 2026-09-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_journalentry_source_openingbalancesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_subtype',
            field=models.CharField(blank=True, choices=[('KAS_SETARA_KAS', 'Kas dan Setara Kas'), ('PIUTANG_USAHA', 'Piutang Usaha'), ('PIUTANG_LAINNYA', 'Piutang Lainnya'), ('PERSEDIAAN', 'Persediaan'), ('BIAYA_DIBAYAR_DIMUKA', 'Biaya Dibayar Dimuka'), ('ASET_TETAP', 'Aset Tetap'), ('ASET_TAKBERWUJUD', 'Aset Takberwujud'), ('INVESTASI', 'Investasi'), ('ASET_LAINNYA', 'Aset Lainnya'), ('UTANG_USAHA', 'Utang Usaha'), ('UTANG_LAINNYA', 'Utang Lainnya'), ('UTANG_PAJAK', 'Utang Pajak'), ('LIABILITAS_KEUANGAN', 'Liabilitas Keuangan'), ('PENDAPATAN_DITERIMA_DIMUKA', 'Pendapatan Diterima Dimuka'), ('UTANG_JANGKA_PANJANG', 'Utang Jangka Panjang'), ('EKUITAS', 'Ekuitas'), ('PENDAPATAN', 'Pendapatan'), ('PENDAPATAN_LAIN_LAIN', 'Pendapatan Lain-lain'), ('BEBAN_POKOK_PENJUALAN', 'Beban Pokok Penjualan'), ('BEBAN_USAHA', 'Beban Usaha'), ('BEBAN_LAIN_LAIN', 'Beban Lain-lain')], default='', help_text='Menentukan posisi akun di laporan keuangan secara otomatis (mengisi Tipe Akun & Saldo Normal). Opsional untuk akun lama.', max_length=40, verbose_name='Sub-Tipe Akun'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_contra',
            field=models.BooleanField(default=False, help_text='Akun kontra dikurangkan dari total, bukan ditambahkan — contoh: Akumulasi Penyusutan, Cadangan Kerugian Piutang. Membalik Saldo Normal yang diturunkan dari Sub-Tipe Akun.', verbose_name='Akun Kontra'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_control_account',
            field=models.BooleanField(default=False, help_text='Akun kontrol tidak dapat menerima entri jurnal manual — saldonya harus selalu sama dengan total sub-ledger terkait (mis. AR harus sama dengan total tagihan pelanggan).', verbose_name='Akun Kontrol'),
        ),
    ]
