# Generated by Django 5.0.14 on 2026-09-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_backfill_account_subtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Menjadikan akun ini sebagai sub-akun dari akun lain — murni untuk pengelompokan tampilan (mis. beberapa Kas Kecil di bawah satu Kas & Bank). TIDAK mempengaruhi Account.balance() atau laporan mana pun — lihat class docstring Account di atas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='Sub-Akun Dari'),
        ),
    ]
