# Generated by Django 5.0.14 on 2026-09-10 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_account_parent'),
        ('organizations', '0005_organization_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField(verbose_name='Tanggal Transaksi')),
                ('description', models.CharField(max_length=255, verbose_name='Keterangan')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positif untuk uang masuk, negatif untuk uang keluar.', max_digits=14, verbose_name='Jumlah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_lines', to='accounting.account', verbose_name='Akun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dicatat Oleh')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Bank Statement Line',
                'verbose_name_plural': 'Bank Statement Lines',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='accounting.journalline', verbose_name='Baris Jurnal')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dicocokkan Oleh')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('statement_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='accounting.bankstatementline', verbose_name='Baris Rekening Koran')),
            ],
            options={
                'verbose_name': 'Reconciliation Match',
                'verbose_name_plural': 'Reconciliation Matches',
                'ordering': ['-matched_at'],
                'unique_together': {('statement_line', 'journal_line')},
            },
        ),
    ]
