# Generated by Django 5.0.14 on 2026-09-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_bankstatementline_reconciliationmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reverses',
            field=models.ForeignKey(blank=True, help_text='Jika entri ini adalah pembalikan (reversal) dari entri lain, merujuk ke entri asli tersebut.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='accounting.journalentry', verbose_name='Membalik Entri'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('DOMAIN_EVENT', 'Event Domain'), ('MANUAL', 'Jurnal Manual'), ('PERIOD_CLOSING', 'Penutupan Periode'), ('ASSET_ACQUISITION', 'Perolehan Aset'), ('DEPRECIATION', 'Penyusutan Aset'), ('OPENING_BALANCE', 'Saldo Awal'), ('CORRECTION', 'Koreksi Periode Tertutup')], max_length=20, verbose_name='Sumber'),
        ),
    ]
