# Generated by Django 5.0.14 on 2026-09-17 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_backfill_is_control_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalancesession',
            name='confirmed_zero_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dikonfirmasi Nihil'),
        ),
        migrations.AddField(
            model_name='openingbalancesession',
            name='confirmed_zero_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dikonfirmasi Nihil Oleh'),
        ),
    ]
