# Generated by Django 5.0.14 on 2026-08-19 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organization_daily_appointment_capacity'),
        ('service', '0007_servicereminderlog'),
        ('workorders', '0006_workorderjobline_started_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_date', models.DateField(verbose_name='Tanggal Diminta')),
                ('notes', models.TextField(blank=True, help_text="Bebas, misal 'Ganti oli & cek rem' — bukan pilihan paket layanan (belum ada di v1).", verbose_name='Keluhan / Jenis Servis')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Terkonfirmasi'), ('CONVERTED', 'Sudah Datang'), ('CANCELLED', 'Dibatalkan')], default='CONFIRMED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='service.customer', verbose_name='Pelanggan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='service.vehicle', verbose_name='Kendaraan')),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='workorders.workorder', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['requested_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentDayLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Appointment Day Lock',
                'verbose_name_plural': 'Appointment Day Locks',
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
