# Generated by Django 5.0.14 on 2026-08-07 02:59

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_invoice_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(editable=False, unique=True, verbose_name='Event ID')),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='Tipe Event')),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Payload')),
                ('occurred_at', models.DateTimeField(verbose_name='Waktu Kejadian')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Percobaan')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Error Terakhir')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Diproses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
