# Generated by Django 5.0.14 on 2026-07-20 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Pelanggan')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('stnk_name', models.CharField(blank=True, help_text='Nama pemilik terdaftar di STNK, jika berbeda dari nama pelanggan.', max_length=200, verbose_name='Nama di STNK')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, verbose_name='Nomor Plat')),
                ('manufacture_year', models.PositiveIntegerField(verbose_name='Tahun Pembuatan')),
                ('vehicle_type', models.CharField(max_length=100, verbose_name='Jenis Kendaraan')),
                ('model', models.CharField(max_length=100, verbose_name='Type/Model')),
                ('current_odometer_km', models.PositiveIntegerField(default=0, verbose_name='KM Saat Ini')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Service Terakhir')),
                ('last_service_odometer_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Saat Service Terakhir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='service.customer', verbose_name='Pelanggan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['plate_number'],
                'unique_together': {('organization', 'plate_number')},
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField(verbose_name='Tanggal Service')),
                ('odometer_km', models.PositiveIntegerField(verbose_name='KM Saat Service')),
                ('issue_description', models.TextField(verbose_name='Kerusakan')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='Part yang Diganti')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='service.vehicle', verbose_name='Kendaraan')),
            ],
            options={
                'verbose_name': 'Service Record',
                'verbose_name_plural': 'Service Records',
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
