# Generated by Django 5.0.14 on 2026-07-22 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('service', '0002_alter_servicerecord_vehicle_alter_vehicle_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_style',
            field=models.CharField(blank=True, help_text='Sedan, SUV, MPV, dll — kategori bentuk bodi, terpisah dari Jenis Kendaraan.', max_length=100, verbose_name='Jenis Bodi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bpkb_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='No. BPKB'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, help_text='Nomor rangka/NIK sesuai STNK.', max_length=50, verbose_name='No. Rangka'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Warna'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='No. Mesin'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_expiry',
            field=models.DateField(blank=True, help_text='Tanggal jatuh tempo STNK — dasar untuk pengingat perpanjangan di masa depan.', null=True, verbose_name='STNK Berlaku Sampai'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Part')),
                ('sku', models.CharField(blank=True, help_text='Opsional — kode internal bengkel untuk part ini, jika ada.', max_length=50, verbose_name='Kode/SKU')),
                ('unit', models.CharField(default='pcs', help_text='pcs, liter, set, botol, dll.', max_length=20, verbose_name='Satuan')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stok Saat Ini')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Harga jual per satuan saat ini — perubahan di sini tidak mengubah riwayat pemakaian yang sudah tercatat.', max_digits=12, verbose_name='Harga Satuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah')),
                ('unit_price_at_time', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Saat Digunakan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='service.part', verbose_name='Part')),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='service.servicerecord', verbose_name='Catatan Servis')),
            ],
            options={
                'verbose_name': 'Part Usage',
                'verbose_name_plural': 'Part Usages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Perubahan Jumlah')),
                ('reason', models.CharField(choices=[('restock', 'Restock / Pembelian'), ('correction', 'Koreksi Stok'), ('damage', 'Rusak / Hilang')], default='restock', max_length=20, verbose_name='Alasan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='service.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
