# Generated by Django 5.0.14 on 2026-07-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_move_inventory_models_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Perorangan'), ('INSTITUTIONAL', 'Institusi/Tender')], default='INDIVIDUAL', max_length=20, verbose_name='Jenis Pelanggan'),
        ),
    ]
