# Generated by Django 5.0.14 on 2026-08-19 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_invoice_code'),
        ('service', '0006_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('for_last_service_date', models.DateField(verbose_name='Untuk Service Terakhir Tanggal')),
                ('status', models.CharField(choices=[('SENT', 'Terkirim'), ('FAILED', 'Gagal')], max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='service.vehicle', verbose_name='Kendaraan')),
            ],
            options={
                'verbose_name': 'Service Reminder Log',
                'verbose_name_plural': 'Service Reminder Logs',
                'ordering': ['-sent_at'],
                'unique_together': {('vehicle', 'for_last_service_date')},
            },
        ),
    ]
