# Generated by Django 5.0.14 on 2026-08-08 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_stockadjustment_reason'),
        ('organizations', '0003_alter_organization_invoice_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor GRN')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('received_at', models.DateTimeField(verbose_name='Waktu Diterima')),
                ('reference', models.CharField(blank=True, help_text='Nomor surat jalan supplier, dll — opsional.', max_length=100, verbose_name='Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diterima Oleh')),
            ],
            options={
                'verbose_name': 'Goods Received Note',
                'verbose_name_plural': 'Goods Received Notes',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedNoteLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Beli Satuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods_received_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchasing.goodsreceivednote', verbose_name='GRN')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_line_items', to='inventory.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Goods Received Line Item',
                'verbose_name_plural': 'Goods Received Line Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Supplier')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Kontak')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='purchasing.supplier', verbose_name='Supplier'),
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor Internal')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('supplier_invoice_number', models.CharField(blank=True, help_text='Nomor invoice asli dari supplier, jika ada.', max_length=100, verbose_name='Nomor Invoice Supplier')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('invoice_date', models.DateField(verbose_name='Tanggal Invoice')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo')),
                ('status', models.CharField(choices=[('UNPAID', 'Belum Dibayar'), ('PAID', 'Lunas')], default='UNPAID', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='purchasing.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
                'verbose_name_plural': 'Supplier Invoices',
                'ordering': ['-invoice_date'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='purchasing.supplierinvoice', verbose_name='Invoice Supplier'),
        ),
        migrations.CreateModel(
            name='GoodsReceivedNoteSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Goods Received Note Sequence',
                'verbose_name_plural': 'Goods Received Note Sequences',
                'unique_together': {('organization',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceivednote',
            unique_together={('organization', 'number')},
        ),
        migrations.CreateModel(
            name='SupplierInvoiceSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Supplier Invoice Sequence',
                'verbose_name_plural': 'Supplier Invoice Sequences',
                'unique_together': {('organization',)},
            },
        ),
    ]
