# Generated by Django 5.0.14 on 2026-08-13 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_invoice_code'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor Retur')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('return_date', models.DateTimeField(verbose_name='Tanggal Retur')),
                ('reason', models.TextField(verbose_name='Alasan Retur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('goods_received_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchasing.goodsreceivednote', verbose_name='GRN Asal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'ordering': ['-return_date'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Diretur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods_received_note_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_line_items', to='purchasing.goodsreceivednotelineitem', verbose_name='Item GRN Asal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchasing.purchasereturn', verbose_name='Retur Pembelian')),
            ],
            options={
                'verbose_name': 'Purchase Return Line Item',
                'verbose_name_plural': 'Purchase Return Line Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Purchase Return Sequence',
                'verbose_name_plural': 'Purchase Return Sequences',
                'unique_together': {('organization',)},
            },
        ),
    ]
