# Generated by Django 5.0.14 on 2026-08-14 14:36

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_purchase_orders(apps, schema_editor):
    """
    Real, confirmed decision: every GoodsReceivedNote that existed
    BEFORE this feature shipped gets a real, explicitly-labeled
    synthetic "legacy" PurchaseOrder — not left nullable forever.
    status="FULLY_RECEIVED" is the only honest value: the goods are
    already in stock. quantity_ordered = quantity_received is the
    only honest synthetic value — there's no real "what was
    originally ordered" to recover for history that predates the
    feature. A distinct "PO-LEGACY/" number prefix, with its own
    independent counter (never touches the real PurchaseOrderSequence)
    — real PO numbering starts clean at PO/00001, and any legacy PO
    is immediately, visually distinguishable in any list without
    opening it.
    """
    GoodsReceivedNote = apps.get_model("purchasing", "GoodsReceivedNote")
    PurchaseOrder = apps.get_model("purchasing", "PurchaseOrder")
    PurchaseOrderLineItem = apps.get_model("purchasing", "PurchaseOrderLineItem")

    for grn in GoodsReceivedNote.objects.all():
        po = PurchaseOrder.objects.create(
            organization=grn.organization,
            supplier=grn.supplier,
            number=f"PO-LEGACY/{grn.sequence_number:05d}",
            sequence_number=grn.sequence_number,
            status="FULLY_RECEIVED",
            order_date=grn.received_at.date(),
            notes="Dibuat otomatis untuk data historis sebelum fitur Purchase Order tersedia.",
        )
        for grn_line in grn.line_items.all():
            po_line = PurchaseOrderLineItem.objects.create(
                organization=grn.organization,
                purchase_order=po,
                part=grn_line.part,
                quantity_ordered=grn_line.quantity,
                unit_cost=grn_line.unit_cost,
            )
            grn_line.purchase_order_line_item = po_line
            grn_line.save(update_fields=["purchase_order_line_item"])
        grn.purchase_order = po
        grn.save(update_fields=["purchase_order"])

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockadjustment_reason'),
        ('organizations', '0003_alter_organization_invoice_code'),
        ('purchasing', '0002_purchasereturn_purchasereturnlineitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor PO')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Dipesan'), ('PARTIALLY_RECEIVED', 'Sebagian Diterima'), ('FULLY_RECEIVED', 'Diterima Penuh'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('order_date', models.DateField(verbose_name='Tanggal Pesan')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Perkiraan Tiba')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='purchasing.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Dipesan')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Harga yang disepakati/diperkirakan saat pemesanan — bisa berbeda dari harga aktual saat GRN dicatat.', max_digits=12, verbose_name='Harga Beli Satuan (Perkiraan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_line_items', to='inventory.part', verbose_name='Part')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchasing.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Purchase Order Line Item',
                'verbose_name_plural': 'Purchase Order Line Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceivednotelineitem',
            name='purchase_order_line_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grn_line_items', to='purchasing.purchaseorderlineitem', verbose_name='Item PO'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Purchase Order Sequence',
                'verbose_name_plural': 'Purchase Order Sequences',
                'unique_together': {('organization',)},
            },
        ),
        migrations.RunPython(backfill_legacy_purchase_orders, migrations.RunPython.noop),
    ]