# Generated by Django 5.0.14 on 2026-08-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchaseorder_goodsreceivednote_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='purchasing.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednotelineitem',
            name='purchase_order_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_line_items', to='purchasing.purchaseorderlineitem', verbose_name='Item PO'),
        ),
    ]
