# Generated by Django 5.0.14 on 2026-08-23 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockopnamesession_stockopnamesequence_and_more'),
        ('organizations', '0004_organization_daily_appointment_capacity'),
        ('purchasing', '0005_purchasereturn_return_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPartCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_sku', models.CharField(max_length=100, verbose_name='Kode Part Supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_codes', to='inventory.part', verbose_name='Part')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_codes', to='purchasing.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Part Code',
                'verbose_name_plural': 'Supplier Part Codes',
                'ordering': ['supplier__name'],
                'unique_together': {('part', 'supplier')},
            },
        ),
    ]
