# Generated by Django 5.0.14 on 2026-08-26 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_backfill_part_cost_price'),
        ('organizations', '0004_organization_daily_appointment_capacity'),
        ('purchasing', '0006_supplierpartcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='supplier_invoices/%Y/%m/', verbose_name='File Invoice Supplier'),
        ),
        migrations.CreateModel(
            name='QuickPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('payment_method', models.CharField(choices=[('cash', 'Tunai'), ('bank', 'Transfer Bank')], default='cash', max_length=10, verbose_name='Metode Pembayaran')),
                ('purchased_at', models.DateTimeField(verbose_name='Waktu Pembelian')),
                ('reference', models.CharField(blank=True, help_text='Nomor nota/struk, jika ada.', max_length=100, verbose_name='Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_purchases', to='purchasing.supplier', verbose_name='Dibeli Dari')),
            ],
            options={
                'verbose_name': 'Quick Purchase',
                'verbose_name_plural': 'Quick Purchases',
                'ordering': ['-purchased_at'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='QuickPurchaseLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Beli Satuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_purchase_line_items', to='inventory.part', verbose_name='Part')),
                ('quick_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchasing.quickpurchase', verbose_name='Quick Purchase')),
            ],
            options={
                'verbose_name': 'Quick Purchase Line Item',
                'verbose_name_plural': 'Quick Purchase Line Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickPurchaseSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Quick Purchase Sequence',
                'verbose_name_plural': 'Quick Purchase Sequences',
                'unique_together': {('organization',)},
            },
        ),
    ]
