# Generated by Django 5.0.14 on 2026-07-23 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_alter_stockadjustment_reason'),
        ('organizations', '0002_organization_invoice_code'),
        ('service', '0004_move_inventory_models_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=20, verbose_name='Nomor WO')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('status', models.CharField(choices=[('OPEN', 'Terbuka'), ('IN_PROGRESS', 'Dikerjakan'), ('QC', 'Pemeriksaan Kualitas'), ('DONE', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='OPEN', max_length=20, verbose_name='Status')),
                ('odometer_km_intake', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Saat Masuk')),
                ('received_by', models.CharField(blank=True, max_length=200, verbose_name='Diterima Oleh')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('service_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order', to='service.servicerecord', verbose_name='Catatan Servis')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='service.vehicle', verbose_name='Kendaraan')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrderJobLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Deskripsi Pekerjaan')),
                ('is_done', models.BooleanField(default=False, verbose_name='Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_lines', to='workorders.workorder', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'Work Order Job Line',
                'verbose_name_plural': 'Work Order Job Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderMaterialLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah')),
                ('unit_price_at_time', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Saat Digunakan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_material_lines', to='inventory.part', verbose_name='Part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='workorders.workorder', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'Work Order Material Line',
                'verbose_name_plural': 'Work Order Material Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Work Order Sequence',
                'verbose_name_plural': 'Work Order Sequences',
                'unique_together': {('organization',)},
            },
        ),
    ]
