# Generated by Django 5.0.14 on 2026-07-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Jam Mulai Dikerjakan'),
        ),
    ]
