# Generated by Django 5.0.14 on 2026-07-27 22:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_invoice_code'),
        ('workorders', '0002_workorder_work_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nama Tahap')),
                ('sequence', models.PositiveIntegerField(verbose_name='Urutan')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Mulai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workorders.workorder', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'Work Order Stage',
                'verbose_name_plural': 'Work Order Stages',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='workorderjobline',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_lines', to='workorders.workorderstage', verbose_name='Tahap'),
        ),
    ]
