# Generated by Django 5.0.14 on 2026-07-29 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_invoice_code'),
        ('workorders', '0003_workorderstage_workorderjobline_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderstage',
            name='expected_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Estimasi Durasi (Jam)'),
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Mekanik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Mechanic',
                'verbose_name_plural': 'Mechanics',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workorderstage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='workorders.mechanic', verbose_name='Dikerjakan Oleh'),
        ),
    ]
