# Generated by Django 5.0.14 on 2026-07-31 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_workorderstage_expected_duration_hours_mechanic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workorders.mechanic', verbose_name='Mekanik Penanggung Jawab'),
        ),
    ]
