# Generated by Django 5.0.14 on 2026-08-29 07:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_workorderjobline_started_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('15000000'), max_digits=12, verbose_name='Target Bulanan (Rp)'),
        ),
    ]
