# Generated by Django 5.0.14 on 2026-07-25 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_invoice_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('vehicle_description', models.CharField(blank=True, max_length=255, verbose_name='Deskripsi Kendaraan')),
                ('quoted_description', models.TextField(blank=True, verbose_name='Deskripsi Pekerjaan yang Ditawarkan')),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimasi Biaya')),
                ('reason', models.CharField(choices=[('TOO_EXPENSIVE', 'Harga Terlalu Mahal'), ('WENT_ELSEWHERE', 'Pilih Bengkel Lain'), ('POSTPONED', 'Ditunda Dulu'), ('NOT_NEEDED', 'Diputuskan Tidak Perlu'), ('OTHER', 'Lainnya')], default='OTHER', max_length=20, verbose_name='Alasan Penolakan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('follow_up_status', models.CharField(choices=[('PENDING', 'Belum Dihubungi'), ('CONTACTED', 'Sudah Dihubungi'), ('CONVERTED', 'Jadi Pelanggan'), ('CLOSED', 'Ditutup')], default='PENDING', help_text='Filter ke PENDING untuk daftar telepon-balik pribadi Made.', max_length=20, verbose_name='Status Follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Rejected Quote',
                'verbose_name_plural': 'Rejected Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
