# Generated by Django 5.0.14 on 2026-08-06 12:49

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_contract_start_date_terminperiod'),
        ('estimates', '0002_estimate_odometer_km_intake'),
        ('organizations', '0003_alter_organization_invoice_code'),
        ('service', '0006_customer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=255, verbose_name='Pengirim')),
                ('subject', models.CharField(max_length=255, verbose_name='Perihal / Ringkasan')),
                ('letter_date', models.DateField(verbose_name='Tanggal Surat')),
                ('received_date', models.DateField(default=datetime.date.today, verbose_name='Tanggal Diterima')),
                ('file', models.FileField(upload_to='incoming_letters/%Y/%m/', verbose_name='File (PDF/Gambar)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_letters', to='service.customer', verbose_name='Pelanggan Terkait')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_letters', to='service.vehicle', verbose_name='Kendaraan Terkait')),
            ],
            options={
                'verbose_name': 'Incoming Letter',
                'verbose_name_plural': 'Incoming Letters',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='Tahun')),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Letter Sequence',
                'verbose_name_plural': 'Letter Sequences',
                'unique_together': {('organization', 'year')},
            },
        ),
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=50, verbose_name='Nomor Surat')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('year', models.PositiveIntegerField(editable=False, verbose_name='Tahun')),
                ('recipient', models.CharField(max_length=255, verbose_name='Kepada')),
                ('subject', models.CharField(max_length=255, verbose_name='Perihal')),
                ('source', models.CharField(choices=[('ESTIMATE_APPROVAL', 'Persetujuan Estimasi'), ('CONTRACT_FUNDS_REQUEST', 'Permohonan Dana Kontrak'), ('STANDALONE', 'Surat Mandiri')], default='STANDALONE', max_length=30, verbose_name='Sumber')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_letters', to='contracts.contractimport', verbose_name='Import Kontrak Terkait')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_letters', to='estimates.estimate', verbose_name='Estimasi Terkait')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Outgoing Letter',
                'verbose_name_plural': 'Outgoing Letters',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'number')},
            },
        ),
    ]
