# Generated by Django 5.0.14 on 2026-08-02 17:05

import apps.customers.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_invoice_code'),
        ('workorders', '0005_workorder_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=apps.customers.models._generate_token, editable=False, max_length=64, unique=True)),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Dicabut')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Dilihat')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='workorders.workorder', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'Tracking Link',
                'verbose_name_plural': 'Tracking Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
