# Generated by Django 5.0.14 on 2026-08-03 11:28

import apps.customers.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0002_organization_invoice_code'),
        ('service', '0006_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=apps.customers.models._generate_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(verbose_name='Kadaluarsa')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Digunakan Pada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_link_tokens', to='service.customer', verbose_name='Pelanggan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Magic Link Token',
                'verbose_name_plural': 'Magic Link Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
