# Generated by Django 5.0.14 on 2026-08-08 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_issued_event_id'),
        ('organizations', '0003_alter_organization_invoice_code'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('method', models.CharField(choices=[('cash', 'Tunai'), ('bank_transfer', 'Transfer Bank'), ('qris', 'QRIS'), ('card', 'Kartu Debit/Kredit'), ('other', 'Lainnya')], default='cash', max_length=20, verbose_name='Metode')),
                ('refunded_at', models.DateTimeField(verbose_name='Waktu Refund')),
                ('reference', models.CharField(blank=True, help_text='Nomor transfer, ID transaksi refund, dll — opsional.', max_length=100, verbose_name='Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='invoicing.invoice', verbose_name='Invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diproses Oleh')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['refunded_at'],
            },
        ),
    ]
