# Generated by Django 5.0.14 on 2026-08-08 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_invoice_code'),
        ('payments', '0002_refund'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('method', models.CharField(choices=[('cash', 'Tunai'), ('bank_transfer', 'Transfer Bank'), ('qris', 'QRIS'), ('card', 'Kartu Debit/Kredit'), ('other', 'Lainnya')], default='bank_transfer', max_length=20, verbose_name='Metode')),
                ('paid_at', models.DateTimeField(verbose_name='Waktu Dibayar')),
                ('reference', models.CharField(blank=True, help_text='Nomor transfer, referensi pembayaran, dll — opsional.', max_length=100, verbose_name='Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibayar Oleh')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='purchasing.supplierinvoice', verbose_name='Invoice Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'ordering': ['paid_at'],
            },
        ),
    ]
