# Generated by Django 5.0.14 on 2026-08-28 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalentry_source'),
        ('organizations', '0004_organization_daily_appointment_capacity'),
        ('payments', '0003_supplierpayment'),
        ('workorders', '0006_workorderjobline_started_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('method', models.CharField(choices=[('cash', 'Tunai'), ('bank', 'Transfer Bank')], default='cash', max_length=10, verbose_name='Metode Pembayaran')),
                ('paid_at', models.DateTimeField(verbose_name='Waktu Dibayar')),
                ('reference', models.CharField(blank=True, help_text='Nomor kwitansi/struk, jika ada.', max_length=100, verbose_name='Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expenses', to='accounting.account', verbose_name='Akun Beban')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_expenses', to='workorders.mechanic', verbose_name='Mekanik')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Operating Expense',
                'verbose_name_plural': 'Operating Expenses',
                'ordering': ['-paid_at'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='OperatingExpenseSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Operating Expense Sequence',
                'verbose_name_plural': 'Operating Expense Sequences',
                'unique_together': {('organization',)},
            },
        ),
    ]
