# Generated by Django 5.0.14 on 2026-09-02 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_address_and_more'),
        ('payments', '0004_operatingexpense_operatingexpensesequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalCashMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('from_account_code', models.CharField(max_length=10, verbose_name='Dari Akun')),
                ('to_account_code', models.CharField(max_length=10, verbose_name='Ke Akun')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('transaction_date', models.DateField(verbose_name='Tanggal Transaksi')),
                ('note', models.CharField(blank=True, help_text="Cosmetic only — e.g. 'Transfer BCA'. No real per-bank ledger account exists yet; see Roadmap Open Decisions.", max_length=255, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Internal Cash Mutation',
                'verbose_name_plural': 'Internal Cash Mutations',
                'ordering': ['-transaction_date', '-sequence_number'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='InternalCashMutationSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Internal Cash Mutation Sequence',
                'verbose_name_plural': 'Internal Cash Mutation Sequences',
                'unique_together': {('organization',)},
            },
        ),
    ]
