# Generated by Django 5.0.14 on 2026-10-09 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_logo'),
        ('payments', '0005_internalcashmutation_internalcashmutationsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRemittance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=30, verbose_name='Nomor')),
                ('sequence_number', models.PositiveIntegerField(editable=False, verbose_name='Nomor Urut')),
                ('tax_type', models.CharField(choices=[('pph23_self_remit', 'PPh 23 Disetor Sendiri'), ('pph_umkm_final', 'PPh Final UMKM (PP 55/2022)')], max_length=20, verbose_name='Jenis Pajak')),
                ('period_year', models.PositiveIntegerField(verbose_name='Tahun Periode')),
                ('period_month', models.PositiveIntegerField(verbose_name='Bulan Periode')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah')),
                ('method', models.CharField(choices=[('cash', 'Tunai'), ('bank', 'Transfer Bank')], default='bank', max_length=10, verbose_name='Metode Pembayaran')),
                ('paid_at', models.DateTimeField(verbose_name='Waktu Dibayar')),
                ('reference', models.CharField(blank=True, help_text='Nomor NTPN/bukti setor, jika ada.', max_length=100, verbose_name='Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Tax Remittance',
                'verbose_name_plural': 'Tax Remittances',
                'ordering': ['-paid_at'],
                'unique_together': {('organization', 'number'), ('organization', 'tax_type', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='TaxRemittanceSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Tax Remittance Sequence',
                'verbose_name_plural': 'Tax Remittance Sequences',
                'unique_together': {('organization',)},
            },
        ),
    ]
