# Generated by hand, matching Django's own autogen shape — 10 Oct 2026
#
# PPh 23 + PPh Final UMKM patch, follow-up: pph23_withheld_amount was
# already being validated and frozen into the posted journal line and
# the PaymentReceived event payload (apps/payments/models.py,
# Payment.record()) but never actually stored on the Payment row
# itself — a real, flagged gap caught via Pak Holan's own feedback
# (a customer's finance team needs to see the withheld amount on the
# payment record itself, to reconcile against the physical Bukti
# Potong, not just trust it lives correctly in the GL).
#
# default=0 on an ALREADY-POPULATED table is a real, deliberate,
# correct backfill for every existing Payment row: every payment
# recorded before this patch shipped was, by construction, recorded
# before PPh 23 withholding was even a concept in this system — "0
# withheld" is the real, accurate historical fact for every one of
# them, not a placeholder. No separate data migration needed.
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_taxremittance_taxremittancesequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pph23_withheld_amount',
            field=models.DecimalField(
                decimal_places=2, default=Decimal('0'), max_digits=12,
                verbose_name='PPh 23 Dipotong',
                help_text='Diisi hanya jika pelanggan institusi memotong PPh 23 langsung saat pembayaran ini.',
            ),
        ),
    ]
