# Generated by Django 5.0.14 on 2026-07-26 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_invoice_code'),
        ('service', '0004_move_inventory_models_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Judul Pekerjaan')),
                ('fiscal_year', models.PositiveIntegerField(verbose_name='Tahun Anggaran')),
                ('termin_count', models.PositiveSmallIntegerField(choices=[(3, '3x per tahun (tiap 4 bulan)'), (4, '4x per tahun (tiap 3 bulan)')], verbose_name='Jumlah Termin')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRED', 'Berakhir'), ('CANCELLED', 'Dibatalkan')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='service.customer', verbose_name='Klien Institusi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='contract_imports/%Y/%m/', verbose_name='File Asli')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Menunggu Peninjauan'), ('APPLIED', 'Diterapkan'), ('REJECTED', 'Ditolak')], default='PENDING_REVIEW', max_length=20, verbose_name='Status')),
                ('parsed_diff', models.JSONField(blank=True, default=dict, verbose_name='Hasil Perbandingan')),
                ('document_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total Tertulis di Dokumen')),
                ('computed_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total Hasil Parsing')),
                ('parse_error', models.TextField(blank=True, verbose_name='Error Parsing')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='contracts.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Import',
                'verbose_name_plural': 'Contract Imports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Anggaran Dialokasikan')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_vehicles', to='contracts.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_vehicles', to='service.vehicle', verbose_name='Kendaraan')),
            ],
            options={
                'verbose_name': 'Contract Vehicle',
                'verbose_name_plural': 'Contract Vehicles',
                'unique_together': {('contract', 'vehicle')},
            },
        ),
        migrations.CreateModel(
            name='ContractLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_no', models.PositiveIntegerField(verbose_name='Nomor Baris Sumber')),
                ('description', models.CharField(max_length=255, verbose_name='Item Pekerjaan')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume')),
                ('unit', models.CharField(max_length=50, verbose_name='Satuan')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Harga Satuan')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jumlah')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('SUPERSEDED', 'Digantikan')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_line_items', to='contracts.contractimport')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='contracts.contractlineitem')),
                ('contract_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='contracts.contractvehicle')),
            ],
            options={
                'verbose_name': 'Contract Line Item',
                'verbose_name_plural': 'Contract Line Items',
                'ordering': ['contract_vehicle', 'source_row_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='contractlineitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('contract_vehicle', 'source_row_no'), name='unique_active_line_item_per_position'),
        ),
    ]
