# Generated by Django 5.0.14 on 2026-07-29 15:08

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('organizations', '0002_organization_invoice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Tanggal Mulai'),
        ),
        migrations.CreateModel(
            name='TerminPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Termin Ke-')),
                ('jatuh_tempo', models.DateField(verbose_name='Jatuh Tempo')),
                ('amount_expected', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Perkiraan Nilai')),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Nilai Realisasi')),
                ('received_at', models.DateField(blank=True, null=True, verbose_name='Tanggal Realisasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termin_periods', to='contracts.contract', verbose_name='Contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Termin Period',
                'verbose_name_plural': 'Termin Periods',
                'ordering': ['sequence'],
                'unique_together': {('contract', 'sequence')},
            },
        ),
    ]
