# Generated by Django 5.0.14 on 2026-07-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invoice_code',
            field=models.CharField(blank=True, default='', help_text="Kode singkat untuk penomoran invoice, mis. 'AM' untuk Arya Motor (menghasilkan INV/REG/AM/0001/2026). Harus diisi sebelum bengkel ini bisa membuat invoice — lihat apps.invoicing.models.Invoice.save() untuk pesan error jika kosong.", max_length=10, verbose_name='Kode Invoice'),
        ),
    ]
