# Generated by Django 5.0.14 on 2026-08-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_invoice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='invoice_code',
            field=models.CharField(blank=True, default='', help_text="Kode singkat untuk penomoran invoice, mis. 'AM' untuk Arya Motor (menghasilkan INV/REG/AM/0001/2026). Diisi otomatis dari nama bengkel saat pendaftaran (lihat Organization.save() /_generate_invoice_code() di bawah) — pemilik bisa mengubahnya kapan saja di Pengaturan Bengkel.", max_length=10, verbose_name='Kode Invoice'),
        ),
    ]
