# Generated by Django 5.0.14 on 2026-08-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_invoice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='daily_appointment_capacity',
            field=models.PositiveIntegerField(default=4, help_text="Made's own confirmed number, 19 Aug — jumlah maksimum janji temu online per hari, mencerminkan ketersediaan mekanik nyata yang berubah-ubah, bukan kapasitas fisik bengkel (Arthasee tidak melacak jadwal mekanik per hari). Bisa diubah kapan saja di Pengaturan Bengkel.", verbose_name='Kapasitas Janji Temu Harian'),
        ),
    ]
