# Generated by Django 5.0.14 on 2026-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_daily_appointment_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Alamat Bengkel'),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Pengaturan Awal Selesai'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telepon Bengkel'),
        ),
    ]
