# Generated by Django 5.0.14 on 2026-09-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='requires_sequential_period_closing',
            field=models.BooleanField(default=True, help_text='Jika aktif (default), periode akuntansi harus ditutup secara berurutan — periode sebelumnya harus ditutup dulu sebelum periode berikutnya bisa ditutup. Nonaktifkan hanya jika bengkel benar-benar membutuhkan fleksibilitas menutup periode di luar urutan.', verbose_name='Wajib Tutup Buku Berurutan'),
        ),
    ]
